** (EXIT from #PID<0.13005.0>) shell process exited with reason: an exception was raised:
    ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 1917ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

        (ecto_sql 3.11.0) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto 3.11.0) lib/ecto/repo/schema.ex:775: Ecto.Repo.Schema.apply/4
        (ecto 3.11.0) lib/ecto/repo/schema.ex:377: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
        (ecto 3.11.0) lib/ecto/repo/schema.ex:273: Ecto.Repo.Schema.insert!/4
        (sami_metrics 0.1.0) lib/sami_metrics/peoples.ex:48: anonymous fn/1 in SamiMetrics.Peoples.insert_all_data/0
        (elixir 1.15.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
        (elixir 1.15.0) lib/task/supervised.ex:36: Task.Supervised.reply/4
